/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'spark' at '16.01.15 4:45' with Gradle 2.0
 *
 * @author spark, @date 16.01.15 4:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
